const AppConstants = {
    CMS_GET_POSTS    : "GET_POST",
    CMS_GET_ARTICLE  : "GET_ARTICLE",
    CMS_GET_CATEGORIES  : "GET_CATEGORIES",
    CMS_GET_CATEGORY_POSTS    : "GET_CATEGORY_POSTS",
    CMS_GET_RELATED_POSTS    : "GET_RELATED_POSTS",
    CMS_TOTAL_POST_PER_PAGE : 20,
    CMS_TOAST_ADD   : "TOAST_ADD",
    CMS_TOAST_REMOVE : "TOAST_REMOVE",
    CMS_GET_CATEGORY : "GET_CATEGORY",
}

module.exports = AppConstants;
  